services:
  app:
    build: .
    container_name: subscriptions
    ports:
      - "8082:8082"
    depends_on:
      - postgres
    environment:
      - BD_HOST=postgres
      - BD_PORT=5432
      - BD_USER=postgres
      - BD_PASSWORD=postgres
      - BD_DBNAME=subscriptions
      - BD_SSL_MODE=disable
      - BD_SCHEMA=public
      - HTTP_PORT=8082
    restart: unless-stopped

  postgres:
    image: postgres:15-alpine
    container_name: postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=subscriptions
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./deploy/migrations:/docker-entrypoint-initdb.d
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres-data:
